version : "3.4"
services:
  db:
    image: mariadb:10.4.8
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3308:3306
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1126
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=1126

  python:
    build: python
    command: uwsgi --socket :8001 --module mysite.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - db

  nginx:
    image: nginx:1.19
    ports:
      - "8000:8000"
    volumes:
      - ./log/nginx/:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - python
